pipeline {
    agent any
        tools {
        nodejs 'Node-Yarn' // This must exactly match the Name you gave it in Step 2
    }
    stages{
        stage('Checkout') {
            steps {
                echo 'Checking out the code...'
                checkout scm
            }
        }
        stage('Build') {
            steps {
                echo 'Building the JS application...'
                    sh 'bash ci/Scripts/build.sh'
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
                    sh 'bash ci/Scripts/test.sh'
            }
        }
        stage('Package') {
            steps {
                echo 'Packaging the application...'
                    sh 'bash ci/Scripts/package.sh'
            }
        }
        stage('Generate Artifacts') {
            steps {
                echo 'Generating artifacts...'
                    sh 'bash ci/Scripts/artifacts-upload.sh'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying the application...'
                    sh 'bash ci/Scripts/deploy.sh'
            }
        }
    }
    post {
        always {
            echo 'Notifying stakeholders...'
            dir('src') {
                sh 'bash ci/Scripts/notify.sh'
            }
        }
    }
}